export const adminRoute = '/admin'
export const loginRoute = '/login'
export const registerRoute = '/register'
export const basketRoute = '/basket'
export const mainRoute = '/'
export const roomRoute = '/room'
